### PR TITLE
Document phpcs' global installation via composer

### PR DESCRIPTION
**Pull request by ADmad**
I removed the `1. Install PHP` step too. I think it's safe to assume anyone looking for a PHP linter already has PHP installed or know how to. :)

### CODE REVIEW

**Comment by ikappas** [comment]
@ADmad Thank you for the mr

**Comment by ADmad** [comment]
Welcome, awaiting new release. :slightly_smiling_face:

**Comment by ikappas** [comment]
@ADmad Did you have a change to run the development version? Any feedback?

**Comment by ADmad** [comment]
I haven't yet. Will try to do so and report back.

**Pull request merged**
