### PR TITLE
Added encoding configuration

### PR DESCRIPTION
**Pull request by josenicomaia**
Added encoding configuration #34

### CODE REVIEW

**Comment by josenicomaia** [comment]
I wasn't able to test the changes. I don't know how to setup the development environment.
The README.md wan't enough.

**Comment by josenicomaia** [comment]
I applied the "diff" at `~/.vscode/extensions/ikappas.phpcs-0.7.0` and it worked fine.

**Comment by weirdan** [comment]
@josenicomaia , it may have worked for 0.7, but you're submitting this against `develop`, so you should really test against that.

`develop` (future 0.8) is **very** different to 0.7, so this actually may do more harm there than good.

`TextDocument.getText()` returns string that's later passed to the stdin of the process started with utf8 IO streams encoding (see `options` hash in `lint` method). So I suspect it will be utf8 on PHPCS stdin, no matter the actual file encoding. See AtomLinter/linter-phpcs#235 for very similar problem, and why it makes sense to keep `--encoding=UTF-8` as the only encoding.

**Comment by ikappas** [comment]
@josenicomaia Thank you for submitting a merger request!

As @weirdan accurately explained the way the latest version works on `develop` is **very** different compared to `0.7` so I am closing this.

**Pull request closed without merging**
